# Generated by Django 3.2.3 on 2021-05-20 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Exemplo: (00) 0000-0000', max_length=16, validators=[django.core.validators.RegexValidator(message='Deve ter 10 ou 11 números. Veja o exemplo.', regex='^[0-9]{10}$')], verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Compania',
                'verbose_name_plural': 'Companias',
                'ordering': ('name',),
            },
        ),
    ]
